

spring:
  application:
    name: crn-backend
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/reysol?useSSL=false
    username: mediuser
    password: Medi2022
    #    username: reysolza_client
#    password: R00t-Password-client
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
#server:
#  servlet:
#    context-path: /reysol-api/

application:
  security:
    jwt:
      #      secret-key: odfsfdsfdsfdsfds
      secret-key: oEhDmMMbHRWo2ZoDcnf8tJue5/i1SjljkGliwweRuC4=
      expiration: 99999999999
      refresh-token:
        expiration: 99999999999